"""Configuration.

Two layers:

- ``Settings``: process-level settings from environment variables (``PESTER_*``).
- ``PesterConfig``: deployment config (clients, recipients, personalities,
  scheduler policy) loaded from the YAML file named by ``PESTER_CONFIG``.
"""

from datetime import time
from enum import StrEnum
from pathlib import Path
from typing import Any, Literal, Self
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

import yaml
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_prefix="PESTER_", env_file=".env", extra="ignore")

    config: Path | None = None
    database_path: Path = Path("pester.sqlite")
    host: str = "127.0.0.1"
    port: int = 8000
    dev_mode: bool = False


class _Strict(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)


class Permission(StrEnum):
    SUBMIT_JOBS = "submit_jobs"
    READ_EVENTS = "read_events"
    PREVIEW = "preview"


class ClientConfig(_Strict):
    token_hash: str
    permissions: frozenset[Permission] = frozenset()
    recipients: frozenset[str] = frozenset()

    @field_validator("token_hash")
    @classmethod
    def _check_hash_format(cls, value: str) -> str:
        if not value.startswith("sha256:"):
            raise ValueError("token_hash must be generated by `pester hash-token`")
        return value


class QuietHours(_Strict):
    start: time
    end: time


class RecipientConfig(_Strict):
    timezone: str = "UTC"
    quiet_hours: QuietHours | None = None
    channels: dict[str, dict[str, Any]] = Field(default_factory=dict)

    @field_validator("timezone")
    @classmethod
    def _check_timezone(cls, value: str) -> str:
        try:
            ZoneInfo(value)
        except (ZoneInfoNotFoundError, ValueError) as exc:
            raise ValueError(f"unknown timezone {value!r}") from exc
        return value

    @property
    def tz(self) -> ZoneInfo:
        return ZoneInfo(self.timezone)


class PersonalityConfig(_Strict):
    type: Literal["neutral", "template", "llm"]
    prompt: str | None = None
    template: str | None = None

    @model_validator(mode="after")
    def _check_body(self) -> Self:
        if self.type == "llm" and not self.prompt:
            raise ValueError("llm personalities require a prompt")
        if self.type == "template" and not self.template:
            raise ValueError("template personalities require a template")
        return self


class SchedulerConfig(_Strict):
    quiet_hours: QuietHours | None = QuietHours(start=time(21, 0), end=time(8, 30))
    min_interval_minutes: int = Field(default=120, ge=0)
    max_messages_per_day: int = Field(default=4, ge=1)
    max_outstanding: int = Field(default=1, ge=1)
    jitter_minutes: int = Field(default=30, ge=0)
    default_answer_within_seconds: int = Field(default=86_400, gt=0)
    debounce_seconds: int = Field(default=20, ge=0)


class PesterConfig(_Strict):
    clients: dict[str, ClientConfig] = Field(default_factory=dict)
    recipients: dict[str, RecipientConfig] = Field(default_factory=dict)
    personalities: dict[str, PersonalityConfig] = Field(
        default_factory=lambda: {"default": PersonalityConfig(type="neutral")}
    )
    scheduler: SchedulerConfig = SchedulerConfig()

    @model_validator(mode="after")
    def _check_references(self) -> Self:
        for name, client in self.clients.items():
            unknown = client.recipients - self.recipients.keys()
            if unknown:
                raise ValueError(f"client {name!r} references unknown recipients: {sorted(unknown)}")
        return self


def load_config(path: Path | None) -> PesterConfig:
    """Load deployment config from YAML. No path means an empty default config."""
    if path is None:
        return PesterConfig()
    data: object = yaml.safe_load(path.read_text())
    return PesterConfig.model_validate(data or {})
